### ISSUE TITLE
Inconsistent highlighting of value and reference parameters

### ISSUE THREAD

**Issue by mliszcz** [tree-sitter/tree-sitter-cpp#164]
Hi,

Value parameters and reference parameters have different syntax highlight groups. Consider this example:
![image](https://user-images.githubusercontent.com/6927259/171135907-c959f804-7482-4a61-8b73-45100302ad11.png)

According to TSCaptureUnderCursor:
* arg1 is {TSVariable, TSParameter} in that order
* arg2 is {TSParameter, TSVariable} (order is reversed)

The colorscheme I'm using indeed has different colors for TSVariable (fg) and TSParameter (red).

I think that this inconsistency is not desired. This seems to be something that should be addressed by the parser, not the colorscheme.

**Comment by jdrouhard** [comment]
This isn't a parser issue, but should be raised in `nvim-treesitter` as a grammar problem. 

The parameters are all `(identifier)` nodes, but the ones that are reference and pointer types are nested under a `(reference_declarator (identifier))` and `(pointer_declarator (identifier))` respectively. The parameter names that are nested under reference/pointer declarators are all ambiguously matched to both normal variables and parameter identifiers and the variable wins out.

My guess is the grammar needs to be smarter about these patterns appearing in `(parameter_declaration ...)`.

**Comment by maxbrunsfeld** [comment]
@jdrouhard ive been thinking that I want to restructure the declarator rules in this grammar and in the C grammar so that they aren’t so recursively nested. I realized that it makes the syntax trees hard to query, and to use in general. I’m thinking we could use a repeated structure to represent the pointer nesting. In particular, it’d be nice if it were easier to reliably target the names in a declaration. Maybe we could make it so that it only becomes nested if you parenthesized the declarator. I haven’t explored the idea carefully yet, just wanted to put the idea on your radar, in case you have thoughts.

**Comment by jdrouhard** [comment]
I'm definitely open to that. It might actually make something I've been trying to fix with this grammar easier (related to user-defined conversion operators).

Quite a few downstream users of these parsers (including neovim core) may/will need to updated for the breaking change but it's probably worth it.

**Comment by jdrouhard** [comment]
Fixed by nvim-treesitter/nvim-treesitter#3204
