### ISSUE TITLE
Error with the following valid C++ class definition

### ISSUE THREAD

**Issue by srinathava** [tree-sitter/tree-sitter-cpp#188]
The following C++ snippet:

```cpp
// comment
#define EXPORT_CLASS __attribute__ ((visibility("default")))

class EXPORT_CLASS Foobar {
  public:
    unsigned int x;
    virtual double foo(int x) const;
};
```
results in an error node. TS playground reports that the first line after `public:` is an ERROR line. The side-effect in Neovim is that there is no syntax highlighting for that line. Removing the `EXPORT_CLASS` from the class definition seems to fix this issue.

This way of specifying an access specifier is extremely common for exporting classes/functions from a DLL.

(Interestingly, whatever highlighter is used to render markdown language blocks  correctly highlights the `unsigned int x;` line)

**Comment by jdrouhard** [comment]
Dup of #85 and #136. Macros cannot be 100% correctly parsed by a grammar that isn't contextually aware and doesn't run the preprocessor, unfortunately. These ambiguities will always rely on tree-sitter's error recovery.

**Comment by vincentjgoh** [comment]
I would like to argue that in this case, what the macro expands to is actually irrelevant; the token itself will be interpreted in some way by the compiler but shouldn't affect the parsing of the class at all. Why isn't it possible for tree sitter to ignore everything in between `class` and `<Classname>`? 

As it stands, the error recovery as represented in emacs simply breaks everything. clang-format handles the same situation without any issue, and it is also not context aware.

**Comment by amaanq** [comment]
> As it stands, the error recovery as represented in emacs simply breaks everything. clang-format handles the same situation without any issue, and it is also not context aware.

Clang-format is by definition context aware because it uses *clang* in the back to actually understand the code.

**Comment by vincentjgoh** [comment]
@amaanq clang-format absolutely does not do that; it's heuristic based. You might be conflating it with clangd.
But that said, I feel like tree-sitter should not be a regression from using the standard emacs formatter. I have various workarounds (turn off tree-sitter mode for header files, write a defun that toggles between MY_EXPORT_API and __declspec(dllexport), run clang-format on the buffer more often) but it feels like it should be possible for tree-sitter to do a BETTER job than other context-unaware formatters because it's generating so much more info to work with.

Perhaps the thing that I'm ACTUALLY complaining about is that tree-sitter's error recovery seems particularly bad in this case, and that's the thing that should be fixed. I don't need it to understand the macros, just recover from the error slightly better.
