### ISSUE TITLE
bug: `ts_lex` in the checked-in parser.c is malformed

### ISSUE THREAD

**Issue by clarkok** [tree-sitter/tree-sitter-cpp#237]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues of tree-sitter-cpp

### Describe the bug

The generated `ts_lex` in parser.c should start like the belowing. However in the checked-in version of the parser.c the `eof = lexer->elf(lexer);` line is missing. This will cause the parser to stuck in an infinite loop. I personally tried regenerate it locally, and the generated version looks good.

```C
static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);  // <-- this line is missing
  switch (state) {
    // ...
```

### Steps To Reproduce/Bad Parse Tree

N/A, the parsing will never end with the checked-in `parser.c`

### Expected Behavior/Parse Tree

It should not stuck.

### Repro

```cpp
// any code will cause this issue.
void foo() {

}
```

**Comment by amaanq** [comment]
Yeah, we will have an update to core soon that'll keep this consistent - the issue was that the included tree-sitter/parser.h file was scanning absolute paths first before relative (due to the use of angled brackets) when in fact it *should* be using the **bundled** one here. I've fixed that on master.
