### ISSUE TITLE
Handle all string literals

### ISSUE THREAD

**Issue by calixteman** [tree-sitter/tree-sitter-cpp#42]
For reference:
https://en.cppreference.com/w/cpp/language/string_literal

**Comment by nick-prat** [comment]
You can also make custom ones of these. Look at https://github.com/nlohmann/json for an examle

**Comment by maxbrunsfeld** [comment]
I think the current state is that we only handle two of the six:

* [x] " (unescaped_character\|escaped_character)* "
* [ ] `L` " (unescaped_character\|escaped_character)* "
* [ ] `u8` " (unescaped_character\|escaped_character)* "  (since C++11)
* [ ] `u` " (unescaped_character\|escaped_character)* " (since C++11)
* [ ] `U` " (unescaped_character\|escaped_character)* " (since C++11)
* [x] prefix(optional) `R` "delimiter( raw_characters )delimiter"

**Comment by maxbrunsfeld** [comment]
After https://github.com/tree-sitter/tree-sitter-c/pull/25, we're handling 3 of the 6.

**Comment by maxbrunsfeld** [comment]
I think this is done via tree-sitter/tree-sitter-c#36.
